version: '3.9'
services:
  db:
    image: mongo:5.0.14
    ports:
      - "27017:27017"
    volumes: 
      - ~/mongo/data:/data/db
    restart: always
  
  server:
    build: .
    restart: always
    ports:
      - "3000:3000"